/**
 * Build a static location map from 2GIS raster tiles.
 *
 * Why a static image instead of an embedded map widget:
 *  · the map is the LCP-adjacent block on the contacts page, and an iframe
 *    would cost hundreds of KB of third-party JavaScript before it paints;
 *  · a static WebP is ~40–80 KB, is served from our own origin, needs no
 *    cookie consent and works with the strict CSP in next.config.mjs;
 *  · the "Построить маршрут" button already deep-links into the 2GIS app,
 *    which is what a mobile user actually wants (turn-by-turn, not a picture).
 *
 * SOURCE: 2GIS map tiles for the branch's own coordinates
 *         (lat 53.309227, lon 69.396345 — from the 2GIS company card).
 *
 * Usage: node scripts/build-map.mjs
 */
import { mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const LAT = 53.309227;
const LON = 69.396345;
const ZOOM = 16;
const TILE = 256;

// Output crop, sized for a 2:1 block on mobile and desktop.
const OUT_W = 1280;
const OUT_H = 640;

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'public');
const TS_OUT = path.join(ROOT, 'src', 'data', 'map.generated.ts');

// Public tile key used by the 2GIS web client itself.
const TILE_KEY = process.env.TWOGIS_TILE_KEY || '0df33216-aeab-4768-a36b-a4267cafea02';

function worldPixel(lat, lon, zoom) {
  const n = 2 ** zoom;
  const latRad = (lat * Math.PI) / 180;
  const x = ((lon + 180) / 360) * n * TILE;
  const y =
    ((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2) * n * TILE;
  return { x, y };
}

function tileUrl(x, y, zoom) {
  const sub = (x + y) % 4;
  return `https://tile${sub}.maps.2gis.com/v2/tiles?x=${x}&y=${y}&z=${zoom}&v=1&r=g&key=${TILE_KEY}&ts=online_sd`;
}

async function fetchTile(x, y) {
  const res = await fetch(tileUrl(x, y, ZOOM), {
    headers: {
      'User-Agent': 'Mozilla/5.0 (compatible; site-build-script)',
      Referer: 'https://2gis.kz/',
    },
  });
  if (!res.ok) throw new Error(`tile ${x}/${y} -> HTTP ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  const { x: wx, y: wy } = worldPixel(LAT, LON, ZOOM);

  const left = wx - OUT_W / 2;
  const top = wy - OUT_H / 2;

  const minTx = Math.floor(left / TILE);
  const maxTx = Math.floor((left + OUT_W) / TILE);
  const minTy = Math.floor(top / TILE);
  const maxTy = Math.floor((top + OUT_H) / TILE);

  const cols = maxTx - minTx + 1;
  const rows = maxTy - minTy + 1;
  console.log(`Stitching ${cols}×${rows} tiles (z${ZOOM}) around the workshop…`);

  // Assemble on a canvas aligned to the tile grid, then crop.
  const canvasW = cols * TILE;
  const canvasH = rows * TILE;
  const composites = [];

  for (let ty = minTy; ty <= maxTy; ty++) {
    for (let tx = minTx; tx <= maxTx; tx++) {
      const buf = await fetchTile(tx, ty);
      composites.push({
        input: buf,
        left: (tx - minTx) * TILE,
        top: (ty - minTy) * TILE,
      });
    }
  }

  const stitched = await sharp({
    create: {
      width: canvasW,
      height: canvasH,
      channels: 3,
      background: { r: 20, g: 22, b: 26 },
    },
  })
    .composite(composites)
    .png()
    .toBuffer();

  const cropLeft = Math.round(left - minTx * TILE);
  const cropTop = Math.round(top - minTy * TILE);

  const cropped = await sharp(stitched)
    .extract({ left: cropLeft, top: cropTop, width: OUT_W, height: OUT_H })
    .toBuffer();

  // NOTE: no marker is baked into the file on purpose. The map is darkened with
  // a CSS filter to match the dark theme, and a baked red pin would be dragged
  // along by that filter. The pin is drawn in the component instead, so it
  // keeps the exact accent colour and stays crisp at every device pixel ratio.
  await mkdir(OUT_DIR, { recursive: true });
  const mapPath = path.join(OUT_DIR, 'map.webp');
  await sharp(cropped).webp({ quality: 82, effort: 6 }).toFile(mapPath);
  const info = { width: OUT_W, height: OUT_H, size: (await stat(mapPath)).size };

  const lqip = await sharp(cropped)
    .resize({ width: 24 })
    .blur(1)
    .webp({ quality: 42 })
    .toBuffer();

  const ts = `/**
 * AUTO-GENERATED by scripts/build-map.mjs — do not edit by hand.
 *
 * Static location map rendered from 2GIS raster tiles for the workshop's own
 * coordinates (SOURCE: 2GIS firm card, lat ${LAT}, lon ${LON}).
 * Regenerate with: node scripts/build-map.mjs
 */

export const mapImage = {
  src: '/map.webp',
  width: ${info.width},
  height: ${info.height},
  bytes: ${info.size},
  zoom: ${ZOOM},
  lqip: 'data:image/webp;base64,${lqip.toString('base64')}',
} as const;
`;

  await mkdir(path.dirname(TS_OUT), { recursive: true });
  await writeFile(TS_OUT, ts, 'utf8');

  console.log(`✓ public/map.webp  ${info.width}×${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
  console.log('✓ src/data/map.generated.ts');
}

main().catch((err) => {
  console.error('build-map failed:', err);
  process.exit(1);
});
