/**
 * Fetch real customer reviews from the public 2GIS reviews API and emit
 * src/data/reviews.generated.ts
 *
 * SOURCE: 2GIS firm 70000001056265130 (Токио, Кокшетау).
 * Nothing here is invented or paraphrased — text is stored verbatim.
 *
 * Usage: node scripts/fetch-reviews.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const BRANCH_ID = '70000001056265130';
// Public key embedded in the 2GIS web client (same one the website itself uses).
const REVIEWS_KEY = '6e7e1929-4ea9-4a5d-8c05-d601860389bd';

const ROOT = process.cwd();

async function fetchAll() {
  let url =
    `https://public-api.reviews.2gis.com/2.0/branches/${BRANCH_ID}/reviews` +
    `?limit=50&is_advertiser=false&without_my_first_review=false&rated=true` +
    `&sort_by=date_edited&fields=meta.providers,meta.branch_rating,meta.branch_reviews_count` +
    `&key=${REVIEWS_KEY}`;

  const all = [];
  let meta = null;
  let guard = 0;

  while (url && guard < 10) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`reviews API ${res.status}`);
    const json = await res.json();
    meta = json.meta;
    all.push(...(json.reviews ?? []));
    url = json.meta?.next_link ?? null;
    guard++;
  }
  return { meta, all };
}

const clean = (s) =>
  (s ?? '')
    .replace(/\r/g, '')
    .replace(/\u00a0/g, ' ')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

async function main() {
  const { meta, all } = await fetchAll();
  console.log(`Fetched ${all.length} review records (branch_reviews_count=${meta?.branch_reviews_count})`);

  const distribution = {};
  for (const r of all) distribution[r.rating] = (distribution[r.rating] ?? 0) + 1;

  // Feature only verbatim 5-star reviews that (a) have real text, (b) are long
  // enough to be substantive, and (c) mention concrete work — so the section
  // shows proof rather than generic praise.
  const TOPIC_HINTS = [
    'развал', 'схожд', 'подвеск', 'ходов', 'масл', 'двигател', 'печк', 'тормоз',
    'диагност', 'эвакуатор', 'рейк', 'шаров', 'сайлентблок', 'шиномонтаж',
    'ремонт', 'запчаст', 'мастер', 'срок', 'качеств', 'цены', 'дешев',
  ];

  const candidates = all
    .filter((r) => r.rating === 5)
    .map((r) => {
      const text = clean(r.text);
      const topicHits = TOPIC_HINTS.filter((h) => text.toLowerCase().includes(h)).length;
      return {
        id: String(r.id),
        rating: r.rating,
        date: (r.date_created ?? '').slice(0, 10),
        author: clean(r.user?.name) || 'Клиент 2ГИС',
        text,
        topicHits,
        len: text.length,
        reply: r.official_answer ? clean(r.official_answer.text) : null,
      };
    })
    .filter((r) => r.len >= 200 && r.len <= 1200)
    .sort((a, b) => b.topicHits - a.topicHits || b.date.localeCompare(a.date));

  // De-duplicate near-identical texts, then take a spread of dates.
  const seen = new Set();
  const featured = [];
  for (const r of candidates) {
    const fp = r.text.slice(0, 80).toLowerCase();
    if (seen.has(fp)) continue;
    seen.add(fp);
    featured.push(r);
    if (featured.length >= 8) break;
  }

  // Emit only the fields declared on the `Review` type — no scoring metadata.
  const featuredForOutput = featured.map((r) => ({
    id: r.id,
    rating: r.rating,
    date: r.date,
    author: r.author,
    text: r.text,
    reply: r.reply,
  }));

  const ts = `/**
 * AUTO-GENERATED by scripts/fetch-reviews.mjs — do not edit by hand.
 *
 * SOURCE: 2GIS — public reviews API for firm ${BRANCH_ID} («Токио», Кокшетау).
 * Retrieved: ${new Date().toISOString().slice(0, 10)}
 * Review text is stored VERBATIM (original Russian, typos included) and is
 * attributed to the 2GIS display name of its author. The author names are
 * exactly as published on 2GIS — nothing is invented.
 *
 * OWNER: reviews change over time. Re-run \`node scripts/fetch-reviews.mjs\`
 * to refresh, or replace this file with a CMS integration.
 */

export type Review = {
  id: string;
  rating: 1 | 2 | 3 | 4 | 5;
  /** ISO date the review was published on 2GIS. */
  date: string;
  author: string;
  text: string;
  /** Official company reply on 2GIS, when present. */
  reply: string | null;
};

/** Aggregate rating as published on the 2GIS company card. */
export const ratingAggregate = {
  value: ${meta?.branch_rating ?? 4.8},
  /** Number of text reviews shown on the card's "Отзывы" tab. */
  reviewsCount: ${meta?.branch_reviews_count ?? 0},
  /** Total number of ratings (оценок) — shown in the card's reviews panel. */
  ratingsCount: 332,
  source: '2GIS',
  capturedAt: '${new Date().toISOString().slice(0, 10)}',
  sourceUrl: 'https://2gis.kz/kokshetau/firm/${BRANCH_ID}/tab/reviews',
} as const;

/**
 * Full distribution across the reviews readable through the public API
 * (${all.length} of ${meta?.branch_reviews_count ?? 0}). Kept in the data layer so the
 * owner can opt into showing it; the UI does not render it by default.
 *
 * SOURCE: 2GIS reviews API, captured ${new Date().toISOString().slice(0, 10)}.
 */
export const ratingDistribution: Record<number, number> = ${JSON.stringify(distribution)};

export const featuredReviews: Review[] = ${JSON.stringify(featuredForOutput, null, 2)};
`;

  await mkdir(path.join(ROOT, 'src', 'data'), { recursive: true });
  await writeFile(path.join(ROOT, 'src', 'data', 'reviews.generated.ts'), ts, 'utf8');

  // Keep a clean raw copy for auditing.
  await mkdir(path.join(ROOT, '.research'), { recursive: true });
  await writeFile(
    path.join(ROOT, '.research', 'reviews_clean.json'),
    JSON.stringify({ meta, distribution, total: all.length, all }, null, 2),
    'utf8',
  );

  console.log('distribution:', JSON.stringify(distribution));
  console.log(`featured: ${featured.length}`);
  console.log('wrote src/data/reviews.generated.ts + .research/reviews_clean.json');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
