/**
 * Self-host Google Fonts (Manrope + JetBrains Mono, latin + cyrillic subsets).
 *
 * Why: the site must build and run without any third-party requests at runtime,
 * and `next build` must not require network access. Running this script once
 * commits the .woff2 files into /public/fonts and writes src/app/fonts.css.
 *
 * Usage: npm run fonts
 */
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'app', 'fonts.css');

// A modern browser UA is required for Google Fonts to return woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36';

const families = [
  { key: 'Manrope', query: 'Manrope:wght@400;500;600;700;800' },
  { key: 'JetBrainsMono', query: 'JetBrains+Mono:wght@400;500;700' },
];

// Only these subsets are used by the site (Russian + Kazakh + Latin UI text).
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

async function main() {
  if (existsSync(OUT_DIR)) await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const url = `https://fonts.googleapis.com/css2?${families
    .map((f) => `family=${f.query}`)
    .join('&')}&display=swap`;

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`);
  const css = await res.text();

  // Split the stylesheet into @font-face blocks, keeping the preceding comment
  // (which contains the subset name, e.g. /* cyrillic */).
  const blocks = css.split(/(?=@font-face)/g);
  const kept = [];

  for (const block of blocks) {
    if (!block.includes('@font-face')) continue;
    const subsetMatch = block.match(/\/\*\s*([a-z0-9-]+)\s*\*\//i);
    const subset = subsetMatch ? subsetMatch[1].toLowerCase() : 'unknown';
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    const fontStyle = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    if (!family || !weight || !src) continue;

    const fileName = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
    const bin = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`Font download failed (${fileName}): ${bin.status}`);
    await writeFile(path.join(OUT_DIR, fileName), Buffer.from(await bin.arrayBuffer()));

    kept.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        `  font-style: ${fontStyle};`,
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${fileName}') format('woff2');`,
        unicodeRange ? `  unicode-range: ${unicodeRange};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    );
    console.log(`  ✓ ${fileName}  (${subset}, ${weight})`);
  }

  await mkdir(path.dirname(CSS_OUT), { recursive: true });

  const header = [
    '/* AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' * Self-hosted webfonts: Manrope (UI + display) and JetBrains Mono (meta/technical).',
    ' * Re-generate with: npm run fonts',
    ' */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, header + kept.join('\n\n') + '\n', 'utf8');
  console.log(`\nWrote ${kept.length} @font-face rules -> src/app/fonts.css`);
}

main().catch((err) => {
  console.error('fetch-fonts failed:', err);
  process.exit(1);
});
