/**
 * Build responsive image assets for the 17 real 2GIS photos.
 *
 * SOURCE: 2GIS company card 70000001056265130 (Токио, Кокшетау).
 * Originals live in .research/photos_raw/pNN.jpg (see .research/photos_manifest.json).
 *
 * Produces:
 *   public/photos/pNN-<width>.webp        responsive variants
 *   src/data/photo-assets.generated.ts    widths, aspect ratio, LQIP, blurHash-ish
 *   .research/contact-sheet.jpg           dev-only grid so we can curate placement
 *
 * Usage: npm run images
 */
import { mkdir, writeFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const RAW_DIR = path.join(ROOT, '.research', 'photos_raw');
const PUBLIC_DIR = path.join(ROOT, 'public', 'photos');
const RESEARCH_DIR = path.join(ROOT, '.research');
const TS_OUT = path.join(ROOT, 'src', 'data', 'photo-assets.generated.ts');

const WIDTHS = [400, 640, 960, 1440, 1920];
const COUNT = 17;

async function main() {
  if (!existsSync(RAW_DIR)) throw new Error(`Missing ${RAW_DIR}. Run the 2GIS download first.`);
  await mkdir(PUBLIC_DIR, { recursive: true });
  await mkdir(path.dirname(TS_OUT), { recursive: true });

  const entries = [];

  for (let i = 1; i <= COUNT; i++) {
    const id = `p${String(i).padStart(2, '0')}`;
    const src = path.join(RAW_DIR, `${id}.jpg`);
    if (!existsSync(src)) {
      console.warn(`  ! ${id}.jpg missing — skipped`);
      continue;
    }

    const meta = await sharp(src).metadata();
    const natW = meta.width ?? 0;
    const natH = meta.height ?? 0;
    if (!natW || !natH) throw new Error(`${id}: unreadable dimensions`);

    const widths = WIDTHS.filter((w) => w <= natW);
    if (widths.length === 0) widths.push(natW);

    const produced = [];
    for (const w of widths) {
      const out = path.join(PUBLIC_DIR, `${id}-${w}.webp`);
      await sharp(src)
        .rotate() // honour EXIF orientation
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 74, effort: 5, smartSubsample: true })
        .toFile(out);
      const { size } = await stat(out);
      const { height } = await sharp(out).metadata();
      produced.push({ width: w, height: height ?? 0, bytes: size });
    }

    // Low-quality image placeholder (inlined as a data URI, ~120 bytes).
    const lqipBuf = await sharp(src)
      .rotate()
      .resize({ width: 20 })
      .blur(0.6)
      .webp({ quality: 40 })
      .toBuffer();

    entries.push({
      id,
      width: natW,
      height: natH,
      aspect: Number((natW / natH).toFixed(4)),
      lqip: `data:image/webp;base64,${lqipBuf.toString('base64')}`,
      variants: produced,
    });

    const native = produced.find((p) => p.width === widths[widths.length - 1]);
    console.log(
      `  ✓ ${id}  ${natW}x${natH} -> ${produced.length} webp  (largest ${native.width}px, ${(
        native.bytes / 1024
      ).toFixed(0)}KB)`,
    );
  }

  const ts = `/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 *
 * Real photographs of the Токио auto service in Kokshetau, retrieved from the
 * company's public 2GIS gallery (firm id 70000001056265130) on 2026-09-26.
 * \`src\` (the 2GIS original URL) is kept for provenance/attribution.
 * Regenerate with: npm run images
 */

export type PhotoVariant = { width: number; height: number; bytes: number };

export type PhotoAsset = {
  id: string;
  /** Intrinsic dimensions of the 2GIS original. */
  width: number;
  height: number;
  aspect: number;
  /** Tiny inlined WebP used as the loading placeholder. */
  lqip: string;
  variants: PhotoVariant[];
};

export const photoAssets: Record<string, PhotoAsset> = ${JSON.stringify(
    Object.fromEntries(entries.map((e) => [e.id, e])),
    null,
    2,
  )};

export const photoIds = ${JSON.stringify(entries.map((e) => e.id))} as const;

export function largestVariant(id: string): PhotoVariant | undefined {
  const a = photoAssets[id];
  return a ? a.variants[a.variants.length - 1] : undefined;
}
`;

  await writeFile(TS_OUT, ts, 'utf8');

  // Dev-only contact sheet so a human can curate where each photo belongs.
  const thumb = 300;
  const cols = 5;
  const rows = Math.ceil(entries.length / cols);
  const composites = [];
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    const buf = await sharp(path.join(RAW_DIR, `${e.id}.jpg`))
      .rotate()
      .resize({ width: thumb, height: thumb, fit: 'cover' })
      .jpeg({ quality: 70 })
      .toBuffer();
    composites.push({
      input: buf,
      left: (i % cols) * thumb,
      top: Math.floor(i / cols) * thumb,
    });
    // burn the index into the corner
    const label = Buffer.from(
      `<svg width="${thumb}" height="26"><rect width="${thumb}" height="26" fill="#000" opacity="0.72"/><text x="7" y="18" font-family="monospace" font-size="15" fill="#fff">${e.id}  ${e.width}x${e.height}</text></svg>`,
    );
    composites.push({ input: label, left: (i % cols) * thumb, top: Math.floor(i / cols) * thumb });
  }

  await sharp({
    create: {
      width: cols * thumb,
      height: rows * thumb,
      channels: 3,
      background: { r: 10, g: 10, b: 12 },
    },
  })
    .composite(composites)
    .jpeg({ quality: 78 })
    .toFile(path.join(RESEARCH_DIR, 'contact-sheet.jpg'));

  console.log(`\nWrote src/data/photo-assets.generated.ts (${entries.length} photos)`);
  console.log('Wrote .research/contact-sheet.jpg');
}

main().catch((err) => {
  console.error('optimize-images failed:', err);
  process.exit(1);
});
