/**
 * AUTO-GENERATED by scripts/build-map.mjs — do not edit by hand.
 *
 * Static location map rendered from 2GIS raster tiles for the workshop's own
 * coordinates (SOURCE: 2GIS firm card, lat 53.309227, lon 69.396345).
 * Regenerate with: node scripts/build-map.mjs
 */

export const mapImage = {
  src: '/map.webp',
  width: 1280,
  height: 640,
  bytes: 70542,
  zoom: 16,
  lqip: 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAwCdASoYAAwAPulgqE0pJaQiMAgBIB0JZQAAidpM+wAA/u+P/8fWqFTnYa6BkOsgAA==',
} as const;
