/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 *
 * Real photographs of the Токио auto service in Kokshetau, retrieved from the
 * company's public 2GIS gallery (firm id 70000001056265130) on 2026-09-26.
 * `src` (the 2GIS original URL) is kept for provenance/attribution.
 * Regenerate with: npm run images
 */

export type PhotoVariant = { width: number; height: number; bytes: number };

export type PhotoAsset = {
  id: string;
  /** Intrinsic dimensions of the 2GIS original. */
  width: number;
  height: number;
  aspect: number;
  /** Tiny inlined WebP used as the loading placeholder. */
  lqip: string;
  variants: PhotoVariant[];
};

export const photoAssets: Record<string, PhotoAsset> = {
  "p01": {
    "id": "p01",
    "width": 1440,
    "height": 2560,
    "aspect": 0.5625,
    "lqip": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBgCdASoUACQAPuVWqU2pJCQiMBqtUSAciWMAwptYyrSAwH7KebmgFAT1zMcb1K6agr5UbXERDQAA37KibQa2eDzeH7kAcn4u2EBTPQKwDl+lwNZIQkqhnzTuv6NQYSU88HLYS/9E1mqy9zBzma/8oEmceK/XAybsjbSGVOvLVb64yWTZCFExGntuG8fenf6Es6jZUjE/ASfRDMm2N4goG4cLNR4CwmVf2JqlnNrxg0CdxnLCNcaH8YGQAAAA",
    "variants": [
      {
        "width": 400,
        "height": 711,
        "bytes": 32198
      },
      {
        "width": 640,
        "height": 1138,
        "bytes": 75948
      },
      {
        "width": 960,
        "height": 1707,
        "bytes": 148764
      },
      {
        "width": 1440,
        "height": 2560,
        "bytes": 279796
      }
    ]
  },
  "p02": {
    "id": "p02",
    "width": 640,
    "height": 640,
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBQCdASoUABQAPu1mqk8ppaOiKA1RMB2JYgCsAAx1vQfRuITzU19+8oQQgR1VCZnwTAD+wP9hhGgR/rW6PLDi8hezqEyMiv4SZJmnGzEMJUwY1eftPuOLUc0DnuOEPO1rYxM4eJ70I2xRoKBaaRiwaNKUK9ndwBkWnsf19yjjFBaKEt8F+9eVcCE8DHz83HfkoVk7BYwWxUT/C+VQH7AA",
    "variants": [
      {
        "width": 400,
        "height": 400,
        "bytes": 18562
      },
      {
        "width": 640,
        "height": 640,
        "bytes": 31638
      }
    ]
  },
  "p03": {
    "id": "p03",
    "width": 1440,
    "height": 1920,
    "aspect": 0.75,
    "lqip": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAADwBQCdASoUABsAPu1krFAppSQisBgIATAdiUATpmhYMPaWUsXnAgc4OyKkFpKiDWl4jdDof7Ii4ADMn06DrP/B73Ye390K8jDjeW19klGyig3qpU1QyePZ/7fBAnfGdBJxEF1IZuSyBFq6pDkRJy1nwGxlXY8vdYySS0V+fUL5k7jXAPTtrV/jQrLi5wdY+aSC66NfICOEPLKXWRMEtAkuj1tE2MWxN9puC0Yd2GEWRaU0xYD+/eKuNDXiZ/KAAAA=",
    "variants": [
      {
        "width": 400,
        "height": 533,
        "bytes": 30376
      },
      {
        "width": 640,
        "height": 853,
        "bytes": 66240
      },
      {
        "width": 960,
        "height": 1280,
        "bytes": 119066
      },
      {
        "width": 1440,
        "height": 1920,
        "bytes": 211392
      }
    ]
  },
  "p04": {
    "id": "p04",
    "width": 1440,
    "height": 810,
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPu1kqU2ppaOiMAgBMB2JQBWAA9GY3BC3NFRxBeAA/fl8xZrZ/yJwXZi7JBIjHPpxsLUzlnagaHVrZfRY7l1S7BGCeVmHXCihvLlvLhF5QAA=",
    "variants": [
      {
        "width": 400,
        "height": 225,
        "bytes": 13960
      },
      {
        "width": 640,
        "height": 360,
        "bytes": 30882
      },
      {
        "width": 960,
        "height": 540,
        "bytes": 60800
      },
      {
        "width": 1440,
        "height": 810,
        "bytes": 133128
      }
    ]
  },
  "p05": {
    "id": "p05",
    "width": 1440,
    "height": 662,
    "aspect": 2.1752,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoUAAkAPu1mqk2ppaQiMAgBMB2JZQAANx82u866ZGgA/f+IcWCL69yAH/p7Msf2UQQzrWlcAH9XN/EmXCiQDLrf1fZy5UpPoO24AA==",
    "variants": [
      {
        "width": 400,
        "height": 184,
        "bytes": 7438
      },
      {
        "width": 640,
        "height": 294,
        "bytes": 20138
      },
      {
        "width": 960,
        "height": 441,
        "bytes": 47152
      },
      {
        "width": 1440,
        "height": 662,
        "bytes": 111268
      }
    ]
  },
  "p06": {
    "id": "p06",
    "width": 1440,
    "height": 1918,
    "aspect": 0.7508,
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBQCdASoUABsAPu1oqk+ppiOiKA1RMB2JQBdgAbBDoV3pSe/0nJ+Rl7WB8a/1qO+gAN/xsVmwYxVmVSLo1DJ0jEdQMBGY7wJa5REvvtdPOpfj+x670gDOBP4SxTvaxmMThJzohqHQGQ2OacjfRab4yas1i9BVpHC51PCU5f6Kz7KVTg6IaFWlmPERmYEp7v6qXrhI2TrZHjo/HEyi7gAA",
    "variants": [
      {
        "width": 400,
        "height": 533,
        "bytes": 26670
      },
      {
        "width": 640,
        "height": 852,
        "bytes": 53538
      },
      {
        "width": 960,
        "height": 1279,
        "bytes": 89936
      },
      {
        "width": 1440,
        "height": 1918,
        "bytes": 148188
      }
    ]
  },
  "p07": {
    "id": "p07",
    "width": 1440,
    "height": 1084,
    "aspect": 1.3284,
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYwCdMoRwABMzJqJIjXgCJAAA/NV2b3EHDRrNxARrMLRPs2uFmEBVKKdnTYncW/WChpRvf/wltDs4XwVsBQR1campBAAA",
    "variants": [
      {
        "width": 400,
        "height": 301,
        "bytes": 18996
      },
      {
        "width": 640,
        "height": 482,
        "bytes": 45678
      },
      {
        "width": 960,
        "height": 723,
        "bytes": 94448
      },
      {
        "width": 1440,
        "height": 1084,
        "bytes": 199476
      }
    ]
  },
  "p08": {
    "id": "p08",
    "width": 1440,
    "height": 1080,
    "aspect": 1.3333,
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JZwAAXlrwJaYn6D2AyOYwAM4Co4yM5aV9uJBzB85Ts+lzUspeujrjn/K2aMLGQ24VaTrzjigR+h07inJjW4IToU1Ea/o2foAAAA==",
    "variants": [
      {
        "width": 400,
        "height": 300,
        "bytes": 15250
      },
      {
        "width": 640,
        "height": 480,
        "bytes": 30522
      },
      {
        "width": 960,
        "height": 720,
        "bytes": 54246
      },
      {
        "width": 1440,
        "height": 1080,
        "bytes": 97000
      }
    ]
  },
  "p09": {
    "id": "p09",
    "width": 1440,
    "height": 810,
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JYgC06CHm0M+6Mwi0+WrgAP7u2eO3ickTYnEE+jJwDhwC32HiturQCLotTfJWDxySk4xa30dPNwQ2zwz5+4AAAAA=",
    "variants": [
      {
        "width": 400,
        "height": 225,
        "bytes": 11904
      },
      {
        "width": 640,
        "height": 360,
        "bytes": 25562
      },
      {
        "width": 960,
        "height": 540,
        "bytes": 46924
      },
      {
        "width": 1440,
        "height": 810,
        "bytes": 85760
      }
    ]
  },
  "p10": {
    "id": "p10",
    "width": 1440,
    "height": 810,
    "aspect": 1.7778,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAAsAPu1iqk4ppaQiMAgBMB2JQBYdg9Luy8fVcLpTvS9gAM4M0gFe4FY+ytDMywxAhCnU1waWwNwQ4cO+x5pZLh+8fbgovE7KvQAA",
    "variants": [
      {
        "width": 400,
        "height": 225,
        "bytes": 12062
      },
      {
        "width": 640,
        "height": 360,
        "bytes": 27438
      },
      {
        "width": 960,
        "height": 540,
        "bytes": 54676
      },
      {
        "width": 1440,
        "height": 810,
        "bytes": 109070
      }
    ]
  },
  "p11": {
    "id": "p11",
    "width": 640,
    "height": 640,
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASoUABQAPu1oqU+ppiOiKA1RMB2JZwDIXAuXBi8+10fDEGm8v7rhTgdYAPrp7O5PNw1wLv1ViOjgxvk71EgNv7aKfky0FOnvpFK1muWN7jFO5u5oICpqKa6G2v1JTfWGK1KmlEr6zXhyBoSEedZwLqAA",
    "variants": [
      {
        "width": 400,
        "height": 400,
        "bytes": 12080
      },
      {
        "width": 640,
        "height": 640,
        "bytes": 24192
      }
    ]
  },
  "p12": {
    "id": "p12",
    "width": 1440,
    "height": 2560,
    "aspect": 0.5625,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAQBgCdASoUACQAPuVaqE2pJSQiMBqtUSAciWUAxNgQUrqNZQD2Ob4LjksgOEkk/2gTEY2NcwYgiIAA/k9drHvRF83H8BS8fiFIy0VVHgsDT3MUVi5SDGYYW7knswhwCU0PQgdTMiWmnX4nu+BUsz5PmLn5NzeBBuoiqfEqLR5NGIchoMLLiFZ1QgEZ/MGqLm+o0fcTNAz30SDHc82Nh9vJItaJ0svwDsVAAA==",
    "variants": [
      {
        "width": 400,
        "height": 711,
        "bytes": 36862
      },
      {
        "width": 640,
        "height": 1138,
        "bytes": 73902
      },
      {
        "width": 960,
        "height": 1707,
        "bytes": 121770
      },
      {
        "width": 1440,
        "height": 2560,
        "bytes": 192864
      }
    ]
  },
  "p13": {
    "id": "p13",
    "width": 640,
    "height": 640,
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBQCdASoUABQAPu1ur1IppiQiqAgBMB2JYwCdM2QBxO14Vi1jFhHgYuxwEsN4YagAAM3y8RjhrzNRFlezh0PJ70yswU8sfPRSIUM1HuVOVp/xky0zSUe5zrx915m9X6C+2/DFqqqsdU/T6B/SmbUS8B1s6yfCCoGtBv/JHKXSxGRo6zvkXFpSRq2oAAAA",
    "variants": [
      {
        "width": 400,
        "height": 400,
        "bytes": 11904
      },
      {
        "width": 640,
        "height": 640,
        "bytes": 21210
      }
    ]
  },
  "p14": {
    "id": "p14",
    "width": 1440,
    "height": 1920,
    "aspect": 0.75,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBQCdASoUABsAPu1mpU2ppaMiMBgMATAdiWIArDOOwVqaErlVaQ1iC+idIEbyCvkDiMMmgAD+fTPneII0UtLTl16mlsCGLQ8+lMXVjpRqwC14FLs86pwEULzLI3p18AdvwwvuOSgZMOeyCvZGG1sHlCVdD2SijAhE6m58ey3Tuplz71SHT+QncwAAAA==",
    "variants": [
      {
        "width": 400,
        "height": 533,
        "bytes": 14652
      },
      {
        "width": 640,
        "height": 853,
        "bytes": 26544
      },
      {
        "width": 960,
        "height": 1280,
        "bytes": 42830
      },
      {
        "width": 1440,
        "height": 1920,
        "bytes": 70482
      }
    ]
  },
  "p15": {
    "id": "p15",
    "width": 1440,
    "height": 1920,
    "aspect": 0.75,
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBACdASoUABsAPu1irE4ppaSiKA1RMB2JYgBWdQMZhfzN8vZqq37+99qcPoXJQAD9KzmO9OoY/V28r7ym15jk1mD+TgZWoRRh3jH8QCaAUEVM4rh8Ze3PC91fnvNnSQ4/5ky5zYsPmxXAwhTQHHK4caIS6zmXz+1aUtawZgAAAA==",
    "variants": [
      {
        "width": 400,
        "height": 533,
        "bytes": 28932
      },
      {
        "width": 640,
        "height": 853,
        "bytes": 63646
      },
      {
        "width": 960,
        "height": 1280,
        "bytes": 118436
      },
      {
        "width": 1440,
        "height": 1920,
        "bytes": 225248
      }
    ]
  },
  "p16": {
    "id": "p16",
    "width": 640,
    "height": 640,
    "aspect": 1,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoUABQAPu1qq1EppaOiqAqpMB2JZQAAIhpZrrH3njDPrj0SbShd5niMPAAA/mPImVG7MPpIhczooRBfXYbCZQTQSSP5N6ok1Q+7+dIu9aCWpT5cp6IMVXEygPF64kaa5/+nzGqNqkgJYVNNsWzEwAAA",
    "variants": [
      {
        "width": 400,
        "height": 400,
        "bytes": 12796
      },
      {
        "width": 640,
        "height": 640,
        "bytes": 25786
      }
    ]
  },
  "p17": {
    "id": "p17",
    "width": 1440,
    "height": 1920,
    "aspect": 0.75,
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBQCdASoUABsAPu1mrE8ppaQiKA1RMB2JZwAALcwiJEgkp+vvvq/RCcdGuu07itzAAP7uk8amj2z29zVDz4nIxmWq01ji2s+z/lrHQKpkgJq0z1FzWj/0z6Z08OD2+EnXAOLewR84vb/ZZiqD0Zd9uFUMMDTHycAAAA==",
    "variants": [
      {
        "width": 400,
        "height": 533,
        "bytes": 13906
      },
      {
        "width": 640,
        "height": 853,
        "bytes": 26794
      },
      {
        "width": 960,
        "height": 1280,
        "bytes": 46536
      },
      {
        "width": 1440,
        "height": 1920,
        "bytes": 79926
      }
    ]
  }
};

export const photoIds = ["p01","p02","p03","p04","p05","p06","p07","p08","p09","p10","p11","p12","p13","p14","p15","p16","p17"] as const;

export function largestVariant(id: string): PhotoVariant | undefined {
  const a = photoAssets[id];
  return a ? a.variants[a.variants.length - 1] : undefined;
}
